version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    links:
      - 'flask'
  flask:
      container_name: flask
      build: '.'
      ports:
        - '5000'