version: '3'

services:
  nginx:
    image: 'nginx'
    volumes:
      - './nginx.deploy.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'flask'
  flask:
      container_name: flask
      image: 'subacc09/circruit:alpha'
      ports:
        - '5000'